1 'Get your kettle'
2 'Pour some water inside'
3 'Put the kettle on fire since you have put water inside'
4 'Wash your cup'
5 'Wait like 4 minutes'
6 'When it is 4 minutes already'
7 'Pour your warm water into the cup your washed'
8 'Get the your tea bag and milk'
9 'If there is no milk'
10 'Else using only the warm water'
11 'Put your tea bag into the cup where your poured your warm water'
12 'Get your spoon'
13 'Stare the tea with the spoon'
14 'Stare for 2 minutes'
15 'Tea is ready'

